const staffData = [
  {
    id: "001",
    name: "Nguyen Van A",
    rank: "Manager",
    department: "IT",
    hours: 8,
    salary: 5000000,
  },
  {
    id: "002",
    name: "Tran Thi B",
    rank: "Staff",
    department: "HR",
    hours: 7,
    salary: 4000000,
  },
  {
    id: "003",
    name: "Le Van C",
    rank: "Developer",
    department: "IT",
    hours: 9,
    salary: 6000000,
  },
  {
    id: "004",
    name: "Pham Thi D",
    rank: "Supervisor",
    department: "Finance",
    hours: 10,
    salary: 7000000,
  },
  {
    id: "005",
    name: "Hoang Van E",
    rank: "Analyst",
    department: "Marketing",
    hours: 8,
    salary: 5500000,
  },
  {
    id: "006",
    name: "Ngoc Minh F",
    rank: "Support",
    department: "Customer Service",
    hours: 7,
    salary: 4200000,
  },
  {
    id: "007",
    name: "Dinh Tien G",
    rank: "Engineer",
    department: "Production",
    hours: 9,
    salary: 6300000,
  },
  {
    id: "008",
    name: "Ly Thu H",
    rank: "Manager",
    department: "Operations",
    hours: 10,
    salary: 7500000,
  },
  {
    id: "009",
    name: "Tran Van I",
    rank: "Technician",
    department: "IT",
    hours: 8,
    salary: 4800000,
  },
  {
    id: "010",
    name: "Nguyen Thi J",
    rank: "Assistant",
    department: "HR",
    hours: 7,
    salary: 4100000,
  },
  ...Array(10).fill({
    id: "999",
    name: "Pham Van D",
    rank: "Intern",
    department: "Finance",
    hours: 6,
    salary: 3000000,
  }),
];

export default staffData;
